export const music_list = {
  music_1 : 'ASSETS/Musics/Acoustic/adaytoremember.mp3',
  music_2 : 'ASSETS/Musics/Acoustic/love.mp3',
  music_3 : 'ASSETS/Musics/Acoustic/november.mp3',
  music_4 : 'ASSETS/Musics/Acoustic/pianomoment.mp3',
  music_5 : 'ASSETS/Musics/Acoustic/sadday.mp3',
  music_6 : 'ASSETS/Musics/Electronic/dubstep.mp3',
  music_7 : 'ASSETS/Musics/Electronic/house.mp3',
  music_8 : 'ASSETS/Musics/Electronic/moose.mp3',
  music_9 : 'ASSETS/Musics/Electronic/scifi.mp3',
  music_10 : 'ASSETS/Musics/Electronic/summer.mp3',
  music_11 : 'ASSETS/Musics/Jazz/hipjazz.mp3',
  music_12 : 'ASSETS/Musics/Jazz/jazzcomedy.mp3',
  music_13 : 'ASSETS/Musics/Jazz/jazzyfrenchy.mp3',
  music_14 : 'ASSETS/Musics/Jazz/romantic.mp3',
  music_15 : 'ASSETS/Musics/Jazz/theelevatorbossanova.mp3',
  music_16 : 'ASSETS/Musics/Jazz/thejazzpiano.mp3',
  music_17 : 'ASSETS/Musics/Pop/erf.mp3',
  music_18 : 'ASSETS/Musics/Pop/happiness.mp3',
  music_19 : 'ASSETS/Musics/Pop/sweet.mp3',
  music_20 : 'ASSETS/Musics/R&B/groovyhiphop.mp3',
  music_21 : 'ASSETS/Musics/Rock/anewbeginning.mp3',
  music_22 : 'ASSETS/Musics/Rock/beyondtheline.mp3',
  music_23 : 'ASSETS/Musics/Rock/happyrock.mp3',
  music_24 : 'ASSETS/Musics/Rock/highoctane.mp3',
  music_25 : 'ASSETS/Musics/Rock/punky.mp3',
  music_26 : 'ASSETS/Musics/Rock/rumble.mp3',
}